### ISSUE TITLE
Example SPARQL queries return no results

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/RDF-platform#12]
Most of the queries at https://www.ebi.ac.uk/rdf/services/sparql seem to be returning "No results for this query!" (via my browser). 

For example [this query](https://www.ebi.ac.uk/rdf/services/sparql?query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0D%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0D%0APREFIX+dc%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E%0D%0APREFIX+dcterms%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0D%0APREFIX+dbpedia2%3A+%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0D%0APREFIX+dbpedia%3A+%3Chttp%3A%2F%2Fdbpedia.org%2F%3E%0D%0APREFIX+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0D%0A%0D%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E+%0D%0ASELECT+%3Fchild+%3FchildLabel+%3Fparent+%3FparentLabel%0D%0AFROM+%3Chttp%3A%2F%2Frdf.ebi.ac.uk%2Fdataset%2Fefo%3E+%0D%0A+++WHERE+%7B%0D%0A+++%3Fchild+rdfs%3AsubClassOf+%3Fparent+.%0D%0A+++%3Fchild+rdfs%3Alabel+%3FchildLabel+.%0D%0A+++%3Fparent+rdfs%3Alabel+%3FparentLabel+.%0D%0A+++%7D&render=HTML&limit=25&offset=0#loadstar-results-section) to "Get the IRI and the label for all children and their parents in EFO":

> ![image](https://user-images.githubusercontent.com/1117703/94475995-e184c480-019d-11eb-810c-72f6f40b0866.png)

Is some component of the backend down?

**Comment by lubianat** [comment]
Got the same issue here for a couple different queries too

**Comment by fgiacomoni** [comment]
Yes same no-result, a couple of weeks later... I'm going to mail rdf-req[at]ebi.ac.uk?

**Comment by henrietteharmse** [comment]
The RDF-Platform has been terminated due to funding restrictions.

**Comment by fgiacomoni** [comment]
Thank you for the reply - we will work with last available dump.

**Comment by dhimmel** [comment]
> The RDF-Platform has been terminated due to funding restrictions.

Thanks @henrietteharmse for the information. I thought that might be the case, since the about page at https://www.ebi.ac.uk/rdf/about/ includes:

> Unfortunately the RDF Platform has no funding currently and as such support of this service is sporadic at best. If you are depending on the RDF Platform in your organization, or you are willing to consider funding the RDF platform, please contact us at rdf-req@ebi.ac.uk with details regarding your project.

I wonder if it'd be possible to add that yellow banner to https://www.ebi.ac.uk/rdf/services/sparql. I forget how I came to this link, but it wasn't via any of the pages with the out of operation notice.

If any funders see this, +1 to restoring this service, as it seems like it'd be really useful for programmatic access to the great knowledgebases EBI is compiling.
