### ISSUE TITLE
SPARQL endpoint not working

### ISSUE THREAD

**Issue by fstrozzi** [EBISPOT/RDF-platform#9]
Hello,
It seems there is a problem with the RDF platform right now, as I am not able to run any query on the SPARQL endpoint and even all the examples queries from the browser are failing, with this main error reported: 

```
HTTP Status 500 - Request processing failed; nested exception is java.lang.IllegalStateException: Ambiguous @ExceptionHandler method mapped for [class uk.ac.ebi.fgpt.lode.exception.LodeException]
```

and 

```
The server encountered an internal error that prevented it from fulfilling this request
```

Any idea on what is happening ? 

Thanks you very much !
Francesco

**Comment by simonjupp** [comment]
Hi Francesco! 
Virtuoso fell over and our monitoring and fallback scripts didn't recover it properly! It should be back now. Thanks for reporting.

**Comment by fstrozzi** [comment]
Thanks @simonjupp ! 
Works perfectly now.

Cheers
Francesco
